riot:
  api:
    key: ${RIOT_API_KEY}
spring:
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
    path: /v3/api-docs
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
